// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Explicitly define the sidebar structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: Robotic Nervous System (ROS 2)',
      items: [
        'module1_ros2/index',
        'module1_ros2/ros2_basics',
        'module1_ros2/python_ros',
        'module1_ros2/urdf_humanoids'
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module2_digital_twin/index',
        'module2_digital_twin/physics_sim'
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module3_ai_robot_brain/index',
        'module3_ai_robot_brain/isaac_intro',
        'module3_ai_robot_brain/vslam',
        'module3_ai_robot_brain/path_planning',
        'module3_ai_robot_brain/reinforcement_learning'
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module4_vla/index',
        'module4_vla/whisper_integration',
        'module4_vla/nlp_to_ros'
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Module 5: RAG Chatbots for Robotics',
      items: [
        'module5_rag_chatbots/index'
      ],
      collapsed: false
    }
  ]

  // Alternative: Use autogenerated structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
